#!/bin/bash

test_dockerfile_ubuntu_runs_ubuntu() {
  assert 'expect -d <<EOF
set timeout 10
log_user 0
spawn ./run_tests_ubuntu.sh -d
expect {
  timeout { send_user "Failed to get prompt\n"; exit 1 }
  eof { send_user "Failed to launch docker \n"; exit 1 }
  -re "root@.*:.*/tests# .*"
}
send "cat /etc/issue.net\n"
expect {
  timeout { send_user "Did not match ubuntu version\n"; exit 1 }
  -re "Ubuntu 16\.04.*"
}
send "exit\n"
expect "exit"
EOF
'
}

setup() {
  test_prefix=test_ # workaround for bash_unit not to try to run this test on first pass
  cat > test_plumb_unit_ubuntu <<EOF
#!/bin/bash
EOF
  ln -s run_tests.sh run_tests_ubuntu.sh
}

teardown() {
  rm test_plumb_unit_ubuntu
  rm run_tests_*.sh 2>/dev/null
}

assert "expect -v" "expect needs to be installed to run this tests"

